# Modified from https://github.com/actions/starter-workflows/blob/main/ci/dotnet-desktop.yml

name: Build artifacts

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_call:

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        runtime: [ "win-x64", "osx-arm64", "linux-x64" ]
        include:
          - runtime: "win-x64"
            os: "windows-latest"
          - runtime: "osx-arm64"
            os: "macos-latest"
          - runtime: "linux-x64"
            os: "ubuntu-latest"

    permissions:
      id-token: write
      contents: read
      attestations: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build the application
      run: dotnet publish --configuration Release -r ${{ matrix.runtime }}

    - name: Move artifacts - Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: Move-Item -Path TuneLab\bin\Release\net8.0\${{ matrix.runtime }}\publish -Destination workspace

    - name: Move artifacts - MacOS and Linux
      if: runner.os != 'Windows'
      run: mv TuneLab/bin/Release/net8.0/${{ matrix.runtime }}/publish workspace

    - name: Generate artifact attestation - Windows
      if: runner.os == 'Windows'
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: '"workspace/*.dll","workspace/*.exe"'

    - name: Generate artifact attestation - MacOS and Linux
      if: runner.os != 'Windows'
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: '"workspace/*.dll","workspace/ExtensionInstaller","workspace/TuneLab"'

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TuneLab-${{ matrix.runtime }}-${{github.sha}}
        path: workspace

